### ISSUE TITLE
No CSS

### ISSUE THREAD

**Issue by RedGuy12** [scratchdit/scratchdit#21]
The theme files were dynamically created during setup. But now that it's been more than 30 minutes since then, heroku reset the filesystem. aka, it's an ephemeral filesystem. Now, all the CSS files are 404s, meaning we have no CSS.

**Comment by jemunm378** [comment]
@RedGuy12 For some reason I still can’t see the css on my end?

**Comment by RedGuy12** [comment]
Yeah...#20 didn't work for some reason
________________________________

**Comment by RedGuy12** [comment]
See #19
