### ISSUE TITLE
Images are corrupt

### ISSUE THREAD

**Issue by RedGuy12** [scratchdit/scratchdit#24]
All of our images are corrupt and I can't seem to find new versions anywhere.

**Comment by RedGuy12** [comment]
Recusion by https://github.com/scratchdit/scratchdit/commit/21742aceef6bd7647c5338eaf3f24a82d6747e13

**Comment by jemunm378** [comment]
How did it got corrupted?

**Comment by RedGuy12** [comment]
Not sure...i think it might have been from moving the files off my other server, see #22
________________________________

**Comment by RedGuy12** [comment]
Not fixed on admin dashboard
