### ISSUE TITLE
Having problems signing up... again

### ISSUE THREAD

**Issue by jemunm378** [scratchdit/scratchdit#28]
@RedGuy12 I'm having problems signing up. I my email address and a message below said "you need to enter a valid email address." I did enter a valid email address. I even tried to change it, still didn't work.

**Comment by RedGuy12** [comment]
Same here.

**Comment by RedGuy12** [comment]
Wait idk what you did but i can log in and out now

**Comment by jemunm378** [comment]
I was just re uploading some files. Since that fixed the login issue. I will do all files in the /jsscripts directory.

**Comment by RedGuy12** [comment]
Ohhh... my php linter says use TRUE not true, so I did a global find and replace but in javascript it needs to be lowercase...I just thought I fixed it all


Put it in a pr when you're ready.
________________________________

**Comment by jemunm378** [comment]
@RedGuy12 I'm going to delete the jscripts directory and add it back. wait one second.

**Comment by jemunm378** [comment]
@Redguy12 Still the same issue.

**Comment by jemunm378** [comment]
@Redguy12 Also, did you replace it to the old files? Because that may the problem.

**Comment by jemunm378** [comment]
@RedGuy12 Nevermind. Found the problem. I tried recording the network log and it come up as "{"errors":["Authorization code mismatch. Are you accessing this function correctly? Please go back and try again."]}". [This](https://community.mybb.com/thread-218862.html) can help you fix the issue.
